################################################################################
#                    MCMC DIAGNOSTICS - POST-PROCESSING PIPELINE
#                     PART 3: POST-PROCESSING ANALYSIS & PLOTS
################################################################################
#
# Script: Post-processing diagnostics for Bayesian state-space model
# Author: Jeremy Bourdon (jeremy.bourdon@agrocampus-ouest.fr)
# Date: September 2025
#
# Description:
# This script provides comprehensive post-processing diagnostics for the
# Bayesian state-space model results generated by the parallel MCMC execution.
# It builds upon the existing MCMC results to assess convergence, effective
# sample sizes, and posterior distributions.
#
# Prerequisites:
# 1. Source the MCMC diagnostics functions (mcmc_diagnostics_functions.R)
# 2. MCMC results objects in workspace: mcmc, WAIC_3chains_separate, WAIC_all_chains
# 3. Part 1. Project Setup & Structure executed
# 4. Time_series data frame (raw data frame)
#
# Model Context:
# - Dynamic Factor Analysis with AR(1) structure
# - Multiple latent states with factor loadings
# - Hierarchical variance structure
# - NIMBLE-based Bayesian implementation
#
################################################################################

# ------------------------------
# POST-PROCESSING SETUP
# ------------------------------
# This section prepares the workspace and environment for comprehensive MCMC diagnostics.
# Configure post-processing environment
cat("MCMC DIAGNOSTICS POST-PROCESSING PIPELINE\n")

mcmc <- readRDS("results/mcmc_samples.rds")
WAIC_3chains_separate <- readRDS("results/WAIC_3chains_separate.rds")
#mcmc <- mcmc[-3]
K <- 3

time_series <- read_csv("data/time_series_matrix.csv")
colnames(time_series)[1] <- "year"

# Extract basic dataset information for subsequent analysis
n_series <- ncol(time_series[-1])       # Number of time series (labels)
years <- time_series$year               # Time points for the analysis

# Long format with time series values for plots
ts_long <- time_series %>%
  pivot_longer(
    cols      = -year, 
    names_to  = "label", 
    values_to = "values"
  )

# ------------------------------
# STUDY SYSTEM DEFINITION
# ------------------------------

#' Define population labels
#' This analysis covers time_series distinct populations across 
#' the specific region.
#' Use either the names of the columns of your matrix
#' Or a data frame with the labels names

labels <- as.character(colnames(time_series[-1]))

latent_process <- "RW"             # Specify the latent process of the model: "RE", "RW", or "AR"
analyze_truncated <- FALSE         # Set to TRUE to analyze truncated model (with NA values for n years), FALSE for complete model

# ------------------------------
# CONFIGURATION PARAMETERS
# ------------------------------
# Establishing diagnostic criteria: These thresholds represent established best practices 
# in Bayesian MCMC diagnostics. The Gelman-Rubin threshold of 1.05 indicates adequate 
# convergence, while ESS of 400+ ensures reliable posterior inference. These standards 
# help us objectively assess whether our complex Dynamic Factor Analysis model has 
# converged properly across all parameter dimensions.

#' Global settings for diagnostics and visualization
DIAGNOSTIC_CONFIG <- list(
  # Convergence thresholds
  psrf_threshold = 1.05,        # Gelman-Rubin potential scale reduction factor
  ess_min_threshold = 400,      # Minimum effective sample size
  confidence_level = 0.95,      # Confidence level for diagnostics
  
  # Visualization settings
  flip_axis_threshold = 5,      # Auto-flip axes if more than N labels
  max_display_params = 50,      # Maximum parameters to display in plots
  plot_width = 10,              # Default plot width
  plot_height = 6,              # Default plot height
  
  # Color palette for parameter types
  color_palette = c(
    "#4E79A7", "#59A14F", "#E15759", "#F28E2C", "#76B7B2",
    "#B07AA1", "#EDC948", "#FF9DA7", "#9C755F", "#BAB0AC"
  )
)

# Prerequisite validation: Before diving into diagnostics, we verify that our MCMC 
# results are available and properly formatted. This prevents runtime errors and 
# ensures we're working with valid mcmc.list objects from our Bayesian analysis.
#' Verify MCMC results are available
required_objects <- c("mcmc")
missing_objects <- required_objects[!sapply(required_objects, exists)]

if (length(missing_objects) > 0) {
  stop("Required MCMC results not found: ", paste(missing_objects, collapse = ", "),
       "\nPlease run the parallel MCMC execution first.")
}

cat("✓ MCMC results detected and ready for analysis\n")
cat("✓ Diagnostics functions loaded successfully\n\n")

# ------------------------------------------------------------------------------
#                           MCMC RESULTS VALIDATION
# ------------------------------------------------------------------------------
# FOUNDATIONAL VALIDATION
# This crucial first step examines the structure and integrity of our MCMC results.
# We're essentially performing a "health check" on our sampling chains before proceeding
# with detailed diagnostics. This includes verifying we have the expected number of 
# chains, iterations, and parameters - critical information for interpreting subsequent 
# convergence assessments.

# ------------------------------
# VALIDATE MCMC OBJECT
# ------------------------------
cat("Validating MCMC object...\n")

# Validate input class
if (!inherits(mcmc, "mcmc.list")) {
  stop("Input must be an mcmc.list object from the coda package")
}

# Extract basic properties
n_vars <- coda::nvar(mcmc)
n_chains <- coda::nchain(mcmc)
n_iter <- coda::niter(mcmc)

# Check for empty chains
if (n_chains == 0) {
  stop("MCMC object contains no chains")
}

if (n_iter == 0) {
  stop("MCMC object contains no iterations")
}

# Display basic information
cat("MCMC Object Validation:\n")
cat("  ✓ Valid mcmc.list object\n")
cat("  ✓ Variables:", n_vars, "\n")
cat("  ✓ Chains:", n_chains, "\n")
cat("  ✓ Iterations per chain:", n_iter, "\n")
cat("  ✓ Total samples:", n_chains * n_iter, "\n\n")

mcmc_info <- list(
  n_variables = n_vars,
  n_chains = n_chains,
  n_iterations = n_iter,
  total_samples = n_chains * n_iter,
  variable_names = coda::varnames(mcmc)
)

# ------------------------------
# DIRECTORY FILE CREATION DFA
# ------------------------------
# Output organization: Creating a dedicated results directory ensures our diagnostic 
# outputs are well-organized and easily accessible. This structured approach becomes 
# invaluable when comparing multiple model runs or sharing results with collaborators.

# Create output directory results DFA file : first step
output_directory <- "results/dfa_mcmc_diagnostics"
save_plots <- TRUE

cat("COMPREHENSIVE MCMC DIAGNOSTICS PIPELINE\n")

# Create output directory if saving plots
if (save_plots && !dir.exists(output_directory)) {
  dir.create(output_directory, recursive = TRUE)
  cat("Created output directory:", output_directory, "\n\n")
}

# ------------------------------------------------------------------------------
# CONVERGENCE ASSESSMENT - THE CORE DIAGNOSTIC ENGINE
# ------------------------------------------------------------------------------
# This section implements the Gelman-Rubin diagnostic, the gold standard for assessing 
# MCMC convergence. For our Dynamic Factor Analysis model with hundreds of parameters 
# (latent states, factor loadings, variance components), this diagnostic helps identify 
# which specific parameters may need additional sampling. The automated parameter 
# classification allows us to understand convergence patterns across different model 
# components (e.g., do variance parameters converge differently than factor loadings?).

# Convert to matrix for gelman.diag
mcmc_matrix <- as.matrix(mcmc)
diagnostic_plots <- list()

# ==============================================================================
# TRACEPLOT GENERATION
# ==============================================================================
# PURPOSE: Creates comprehensive traceplots to verify MCMC chain convergence and 
# detect potential label-switching problems in the Dynamic Factor Analysis model. 
# Traceplots are essential visual diagnostics that show parameter evolution across 
# iterations, helping identify mixing issues, convergence problems, or the need 
# for chain amputation.
#
# WHAT IT DOES:
# - Generates traceplots for factor loadings (lambda), latent factors, and intercepts
# - Creates parameter groups for systematic visualization (e.g., all lambda[i,k] for factor k)
# - Applies enhanced plotting with color-coding for multiple chains
# - Identifies problematic chains that may require removal before analysis
# - Provides visual confirmation of chain mixing and stationarity
#
# EXPECTED OUTPUT: 
# - PNG files: traceplot_lambda[k].png, traceplot_factor[k].png, traceplot_mu.png
# - Diagnostic assessment of chain quality and convergence behavior
# - Identification of chains needing amputation due to label-switching
# ==============================================================================

source(file.path(path_scripts, "Traceplots.R"))  
#' Verify if all chains has converged correctly
#' Check if the label-switching problem is present
#' Amputate one or more mcmc chains if necessary in Traceplots.R

# ==============================================================================
# GELMAN-RUBIN CONVERGENCE DIAGNOSTICS
# ==============================================================================
# PURPOSE: Implements the Gelman-Rubin potential scale reduction factor (PSRF) 
# diagnostic to assess MCMC convergence across multiple chains. This is the gold 
# standard for convergence assessment in Bayesian analysis, particularly crucial 
# for complex DFA models with hundreds of interdependent parameters.
#
# MATHEMATICAL FOUNDATION:
# - PSRF compares within-chain variance to between-chain variance
# - Values near 1.0 indicate convergence; values > 1.05 suggest poor convergence
# - Transform option handles parameters on different scales (e.g., log-normal)
# - Multivariate assessment considers parameter correlations
#
# WHAT IT DOES:
# - Computes PSRF for all monitored parameters with robust error handling
# - Automatically classifies parameters by type (factors, loadings, variances)
# - Creates structured diagnostics with convergence flags and rankings
# - Generates parameter-specific convergence summaries and failure reports
# - Provides targeted recommendations for problematic parameter groups
#
# EXPECTED OUTPUT:
# - gelman_diagnostics.csv - Complete PSRF results with parameter classification
# - Console summary showing convergence rates by parameter type
# - Identification of specific parameters requiring attention
# ==============================================================================

source(file.path(path_scripts, "GelmanRubin.R"))

# ==============================================================================
# EFFECTIVE SAMPLE SIZE COMPUTATION
# ==============================================================================
# PURPOSE: Calculates effective sample size (ESS) to quantify MCMC sampling 
# efficiency. ESS measures how many independent samples our correlated chains 
# provide, accounting for autocorrelation. This is critical for DFA models where 
# factor identification constraints can create strong parameter correlations.
#
# STATISTICAL RATIONALE:
# - Raw MCMC samples are correlated; ESS gives "equivalent independent samples"
# - Low ESS indicates high autocorrelation and potential sampling inefficiency
# - Minimum threshold of 400 ESS recommended for reliable posterior inference
# - ESS rates show sampling efficiency relative to total iterations
#
# WHAT IT DOES:
# - Computes ESS for each parameter using coda package algorithms
# - Flags parameters with inadequate sampling efficiency (ESS < 400)
# - Creates parameter-type summaries showing sampling challenges
#
# EXPECTED OUTPUT:
# - ess_diagnostics.csv - ESS values with adequacy flags and efficiency rates
# - Summary statistics by parameter type (min, mean, median ESS)
# - List of critically under-sampled parameters (ESS < 400)
# ==============================================================================

source(file.path(path_scripts, "ESS.R"))

# ==============================================================================
# DIAGNOSTIC SYNTHESIS AND SUMMARY GENERATION
# ==============================================================================
# PURPOSE: Aggregates convergence and efficiency diagnostics into comprehensive 
# summaries that transform raw statistics into actionable insights. This synthesis 
# step moves beyond individual parameter diagnostics to provide systematic 
# model health assessments and targeted recommendations.
#
# ANALYTICAL APPROACH:
# - Combines PSRF and ESS results into parameter-type-specific summaries
# - Calculates overall model convergence rates and efficiency metrics
# - Identifies systematic patterns in convergence failures across parameter groups
# - Generates prioritized lists of problematic parameters for focused attention
# - Creates standardized assessment criteria for model adequacy evaluation
#
# WHAT IT DOES:
# - Computes convergence rates by parameter type (factors, loadings, variances)
# - Generates efficiency summaries showing ESS distributions and adequacy rates
# - Creates consolidated reports highlighting the most problematic parameters
# - Establishes model-wide health indicators for objective quality assessment
# - Provides parameter-specific recommendations based on diagnostic patterns
#
# KEY METRICS:
# - Overall convergence rate: percentage of parameters meeting PSRF < 1.05
# - ESS adequacy rate: percentage of parameters with ESS > 400
# - Parameter-type breakdown: convergence patterns by model component
# - Critical failures: parameters with severe convergence or efficiency issues
#
# EXPECTED OUTPUT:
# - convergence_summary.txt - Human-readable diagnostic report
# - Consolidated CSV files with integrated diagnostics
# - Console summaries for immediate model assessment
# ==============================================================================

source(file.path(path_scripts,"summaryESSGELMAN.R"))

# ==============================================================================
# GELMAN-RUBIN VISUALIZATION
# ==============================================================================
# PURPOSE: Creates visualizations of Gelman-Rubin diagnostics 
# with specialized handling for Dynamic Factor Analysis parameter structure. 
# These plots provide intuitive visual assessment of convergence patterns across 
# different parameter types and factor indices.
#
# WHAT IT DOES:
# - Generates color-coded bar plots showing PSRF values with threshold indicators
# - Creates factor-specific plots for structured parameter interpretation
# - Implements responsive layout (horizontal/vertical) based on parameter count
# - Applies professional styling with clear legends and informative subtitles
# - Handles edge cases like missing parameters or plotting failures gracefully
#
# EXPECTED OUTPUT:
# - gelman_factors_k[1-K].png - Factor-specific convergence plots
# - gelman_loadings_k[1-K].png - Loading-specific convergence plots  
# - gelman_[parameter_type].png - Standard parameter group plots
# ==============================================================================

source(file.path(path_scripts,"Plot.Gelman.R"))

# ==============================================================================
# EFFECTIVE SAMPLE SIZE VISUALIZATION
# ==============================================================================
# PURPOSE: Generates comprehensive ESS diagnostic plots with color-coded adequacy 
# indicators and factor-structured organization. These visualizations help identify 
# sampling efficiency patterns and guide decisions about chain length and sampler 
# configuration for future analyses.
#
# WHAT IT DOES:
# - Creates factor-specific ESS plots for factors[k,t] and lambda[i,k] parameters
# - Generates parameter-type plots for variance, intercept, and other components
# - Implements automatic sorting by ESS value to highlight most problematic cases
# - Adds horizontal reference lines at adequacy threshold (400 ESS)
# - Provides comprehensive adequacy rate statistics in plot annotations
#
# EXPECTED OUTPUT:
# - ess_factors_k[1-K].png - Factor-specific ESS diagnostic plots
# - ess_loadings_k[1-K].png - Loading-specific ESS diagnostic plots
# - ess_[parameter_type].png - Parameter group ESS assessments
# ==============================================================================

source(file.path(path_scripts,"Plot.ESS.R"))

# ------------------------------------------------------------------------------
# MODEL COMPARISON WITH WAIC - BEYOND CONVERGENCE TO MODEL SELECTION
# ------------------------------------------------------------------------------
# WAIC (Widely Applicable Information Criterion) provides model comparison capabilities 
# and model adequacy assessment. For DFA models, WAIC helps validate that our complex 
# factor structure appropriately fits the data without overfitting. Consistency 
# across chains indicates robust model selection, while large differences may signal 
# convergence issues that affect model comparison reliability.

cat("\nMODEL SELECTION AND WAIC ANALYSIS\n")  

if (exists("WAIC_all_chains")) {
  cat("OVERALL MODEL WAIC:\n")
  print(WAIC_all_chains)
  cat("\n")
}

if (exists("WAIC_3chains_separate")) {
  cat("INDIVIDUAL CHAIN WAIC VALUES:\n")
  for (i in seq_along(WAIC_3chains_separate)) {
    cat("Chain", i, "WAIC:\n")
    print(WAIC_3chains_separate[[i]])
    cat("\n")
  }
  
  # Check consistency across chains
  waic_values <- sapply(WAIC_3chains_separate, function(x) x$WAIC)
  waic_range <- max(waic_values) - min(waic_values)
  cat("WAIC Consistency Check:\n")
  cat("  • WAIC range across chains:", round(waic_range, 2), "\n")
  if (waic_range > 10) {
    cat("Large WAIC differences between chains - check convergence\n")
  } else {
    cat("  ✓ WAIC values consistent across chains\n")
  }
}

# ------------------------------------------------------------------------------
# CUSTOM DFA VISUALIZATIONS - TAILORED PLOTS FOR FACTOR ANALYSIS MODELS
# ------------------------------------------------------------------------------
# Generic MCMC plots don't always highlight the specific features important in 
# factor analysis. These specialized visualizations focus on the hierarchical 
# structure of DFA models: factor-specific parameters, state evolution patterns, 
# and variance component behavior. These targeted plots make it easier to identify 
# model-specific convergence patterns and communicate results to domain experts.

source(file.path(path_scripts,"DFA_plots.R"))

# ==============================================================================
# OPTIMIZED EXTRACTION OF y_obs VALUES FROM MCMC OUTPUT
# ==============================================================================
# This script extracts the expected values y_obs[t,i] from MCMC samples and 
# creates summary statistics (mean, 95% credible intervals) for plotting
# against observed data.

source(file.path(path_scripts,"Obs_plot.R"))

#==============================================================================
# FACTOR-BASED REGIONAL CLUSTERING WITH UNCERTAINTY PROPAGATION
#==============================================================================
# PURPOSE: Transforms factor analysis results into interpretable regional groupings
# while preserving Bayesian uncertainty. This clustering approach moves beyond
# traditional post-hoc grouping by integrating the full posterior distribution
# into cluster-level predictions, enabling robust identification of regional
# patterns with proper uncertainty quantification.
#
# WHAT IT DOES:
#  - Extracts and restructures MCMC samples into factor loading matrices
#  - Applies hierarchical clustering with statistically-principled cluster selection
#  - Computes robust cluster centroids using median-based aggregation
#  - Propagates uncertainty from individual posterior samples to cluster predictions
#  - Creates plots including dendrograms and time series
#
# EXPECTED OUTPUT:
#  - Regional cluster assignments with optimal number determination
#  - Cluster centroid profiles showing factor loading patterns
#  - Time series predictions at cluster level with uncertainty bounds
#  - Professional visualizations suitable for both technical and policy communication
#  - Comprehensive clustering summary with statistical validation metrics
# ==============================================================================

source(file.path(path_scripts,"Clustering.R"))

################################################################################
# END OF DFA MCMC DIAGNOSTICS POST-PROCESSING
################################################################################

